import Foundation

actor NotionService {
    static let shared = NotionService()

    // Notion API version - centralized for easy updates
    // Using 2022-06-28 which is stable and well-documented
    private let notionVersion = "2022-06-28"
    private let baseURL = "https://api.notion.com/v1"

    private var settings: NotionSettings { NotionSettings.shared }

    // Rate limiting: ~3 requests/second, we use 500ms between requests
    private var lastRequestTime: Date?
    private let minRequestInterval: TimeInterval = 0.5

    private init() {}

    // MARK: - Public API

    /// Test the connection to Notion API.
    func testConnection() async throws {
        guard settings.isConfigured else {
            throw NotionError.notConfigured
        }

        // Try to retrieve the database to verify access
        let url = URL(string: "\(baseURL)/databases/\(settings.databaseId)")!
        let _ = try await makeRequest(url: url, method: "GET")
    }

    /// Create a new page in the configured database with meeting notes.
    func createPage(for memo: Memo) async throws -> String {
        guard settings.isConfigured else {
            throw NotionError.notConfigured
        }

        let url = URL(string: "\(baseURL)/pages")!

        let body = buildCreatePageBody(for: memo)
        let response = try await makeRequest(url: url, method: "POST", body: body)

        guard let pageId = response["id"] as? String else {
            throw NotionError.invalidResponse
        }

        return pageId
    }

    /// Append blocks to an existing page.
    func appendBlocks(to pageId: String, blocks: [[String: Any]]) async throws {
        let url = URL(string: "\(baseURL)/blocks/\(pageId)/children")!

        // Notion limits to 100 blocks per request
        let chunkedBlocks = blocks.chunked(into: 100)

        for chunk in chunkedBlocks {
            let body: [String: Any] = ["children": chunk]
            let _ = try await makeRequest(url: url, method: "PATCH", body: body)
        }
    }

    /// Sync a memo to Notion (create new or update existing).
    func syncMemo(_ memo: Memo) async throws {
        if let existingPageId = memo.notionPageId {
            // Append update to existing page
            try await appendUpdateBlocks(to: existingPageId, memo: memo)
        } else {
            // Create new page
            let pageId = try await createPage(for: memo)
            await MainActor.run {
                memo.notionPageId = pageId
                memo.syncState = .synced
                memo.lastSyncError = nil
            }
        }
    }

    // MARK: - Request Building

    private func buildCreatePageBody(for memo: Memo) -> [String: Any] {
        var properties: [String: Any] = [
            "Name": [
                "title": [
                    ["type": "text", "text": ["content": memo.title]]
                ]
            ]
        ]

        // Add Date property if available (will silently fail if database doesn't have it)
        let isoFormatter = ISO8601DateFormatter()
        isoFormatter.formatOptions = [.withInternetDateTime]
        properties["Date"] = [
            "date": ["start": isoFormatter.string(from: memo.createdAt)]
        ]

        let children = buildContentBlocks(for: memo)

        return [
            "parent": ["database_id": settings.databaseId],
            "icon": ["type": "emoji", "emoji": "🎙️"],
            "properties": properties,
            "children": children
        ]
    }

    private func buildContentBlocks(for memo: Memo) -> [[String: Any]] {
        var blocks: [[String: Any]] = []

        // Summary section
        blocks.append(heading2("Summary"))
        if let summary = memo.summaryText, !summary.isEmpty {
            blocks.append(paragraph(summary))
        } else {
            blocks.append(paragraph("No summary available."))
        }

        // Decisions section
        blocks.append(heading2("Decisions"))
        if memo.decisions.isEmpty {
            blocks.append(paragraph("None"))
        } else {
            for decision in memo.decisions {
                blocks.append(bulletedListItem(decision))
            }
        }

        // Action Items section
        blocks.append(heading2("Action Items"))
        if memo.actionItems.isEmpty {
            blocks.append(paragraph("None"))
        } else {
            for item in memo.actionItems {
                blocks.append(toDo(item, checked: false))
            }
        }

        // Transcript in a toggle
        blocks.append(toggleWithTranscript(memo.transcriptText ?? ""))

        // Footer
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        blocks.append(paragraph("Generated by Swift Scribe • \(formatter.string(from: memo.createdAt))"))

        return blocks
    }

    private func appendUpdateBlocks(to pageId: String, memo: Memo) async throws {
        var blocks: [[String: Any]] = []

        blocks.append(divider())

        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        blocks.append(heading2("Updated \(formatter.string(from: Date()))"))

        blocks.append(contentsOf: buildContentBlocks(for: memo))

        try await appendBlocks(to: pageId, blocks: blocks)

        await MainActor.run {
            memo.syncState = .synced
            memo.lastSyncError = nil
        }
    }

    // MARK: - Block Builders

    private func heading2(_ text: String) -> [String: Any] {
        [
            "object": "block",
            "type": "heading_2",
            "heading_2": [
                "rich_text": [richText(text)]
            ]
        ]
    }

    private func paragraph(_ text: String) -> [String: Any] {
        // Split into chunks if text is too long (2000 char limit per rich_text element)
        let chunks = text.chunked(into: 2000)
        let richTextElements = chunks.map { richText($0) }

        return [
            "object": "block",
            "type": "paragraph",
            "paragraph": [
                "rich_text": richTextElements
            ]
        ]
    }

    private func bulletedListItem(_ text: String) -> [String: Any] {
        [
            "object": "block",
            "type": "bulleted_list_item",
            "bulleted_list_item": [
                "rich_text": [richText(text)]
            ]
        ]
    }

    private func toDo(_ text: String, checked: Bool) -> [String: Any] {
        [
            "object": "block",
            "type": "to_do",
            "to_do": [
                "rich_text": [richText(text)],
                "checked": checked
            ]
        ]
    }

    private func toggleWithTranscript(_ transcript: String) -> [String: Any] {
        var children: [[String: Any]] = []

        if transcript.isEmpty {
            children.append(paragraph("No transcript available."))
        } else {
            // Split transcript into paragraphs at sentence boundaries
            let sentences = transcript.components(separatedBy: ". ")
            var currentParagraph = ""

            for sentence in sentences {
                if currentParagraph.count + sentence.count > 1800 {
                    if !currentParagraph.isEmpty {
                        children.append(paragraph(currentParagraph))
                    }
                    currentParagraph = sentence + ". "
                } else {
                    currentParagraph += sentence + ". "
                }
            }

            if !currentParagraph.isEmpty {
                children.append(paragraph(currentParagraph.trimmingCharacters(in: .whitespaces)))
            }
        }

        return [
            "object": "block",
            "type": "toggle",
            "toggle": [
                "rich_text": [richText("Transcript")],
                "children": children
            ]
        ]
    }

    private func divider() -> [String: Any] {
        [
            "object": "block",
            "type": "divider",
            "divider": [:]
        ]
    }

    private func richText(_ content: String) -> [String: Any] {
        [
            "type": "text",
            "text": ["content": content]
        ]
    }

    // MARK: - Network

    private func makeRequest(url: URL, method: String, body: [String: Any]? = nil) async throws -> [String: Any] {
        // Rate limiting
        await throttle()

        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("Bearer \(settings.integrationToken)", forHTTPHeaderField: "Authorization")
        request.setValue(notionVersion, forHTTPHeaderField: "Notion-Version")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")

        if let body = body {
            request.httpBody = try JSONSerialization.data(withJSONObject: body)
        }

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse else {
            throw NotionError.invalidResponse
        }

        // Parse response
        let json = try JSONSerialization.jsonObject(with: data) as? [String: Any] ?? [:]

        // Handle errors
        switch httpResponse.statusCode {
        case 200, 201:
            return json

        case 400:
            let message = json["message"] as? String ?? "Bad request"
            // If Date property doesn't exist, retry without it
            if message.contains("Date") {
                throw NotionError.propertyNotFound("Date")
            }
            throw NotionError.badRequest(message)

        case 401:
            throw NotionError.unauthorized

        case 403:
            throw NotionError.forbidden

        case 404:
            throw NotionError.notFound

        case 429:
            let retryAfter = httpResponse.value(forHTTPHeaderField: "Retry-After")
            throw NotionError.rateLimited(retryAfter: Int(retryAfter ?? "") ?? 5)

        default:
            let message = json["message"] as? String ?? "Unknown error"
            throw NotionError.serverError(httpResponse.statusCode, message)
        }
    }

    private func throttle() async {
        if let lastTime = lastRequestTime {
            let elapsed = Date().timeIntervalSince(lastTime)
            if elapsed < minRequestInterval {
                try? await Task.sleep(for: .milliseconds(Int((minRequestInterval - elapsed) * 1000)))
            }
        }
        lastRequestTime = Date()
    }
}

// MARK: - Errors

enum NotionError: LocalizedError {
    case notConfigured
    case invalidResponse
    case badRequest(String)
    case unauthorized
    case forbidden
    case notFound
    case rateLimited(retryAfter: Int)
    case serverError(Int, String)
    case propertyNotFound(String)

    var errorDescription: String? {
        switch self {
        case .notConfigured:
            return "Notion is not configured. Add your token and database ID in Settings."
        case .invalidResponse:
            return "Invalid response from Notion API."
        case .badRequest(let message):
            return "Bad request: \(message)"
        case .unauthorized:
            return "Invalid Notion token. Please check your integration token."
        case .forbidden:
            return "Access denied. Make sure your integration has access to the database."
        case .notFound:
            return "Database not found. Check your database ID and ensure it's shared with your integration."
        case .rateLimited(let retryAfter):
            return "Rate limited. Please try again in \(retryAfter) seconds."
        case .serverError(let code, let message):
            return "Server error (\(code)): \(message)"
        case .propertyNotFound(let property):
            return "Property '\(property)' not found in database schema."
        }
    }
}

// MARK: - Extensions

extension Array {
    func chunked(into size: Int) -> [[Element]] {
        stride(from: 0, to: count, by: size).map {
            Array(self[$0..<Swift.min($0 + size, count)])
        }
    }
}

extension String {
    func chunked(into size: Int) -> [String] {
        var result: [String] = []
        var current = startIndex

        while current < endIndex {
            let end = index(current, offsetBy: size, limitedBy: endIndex) ?? endIndex
            result.append(String(self[current..<end]))
            current = end
        }

        return result
    }
}
